#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

readonly runtime_config_path="${RUNTIME_AUTH_CONFIG_PATH:-js/runtime-auth-config.js}"
readonly default_local_hecateapi_env_file="configs/.env.hecateapi.local"
readonly default_hosted_hecateapi_env_file="configs/.env.hecateapi.production"
readonly default_frontend_config_url="/configs/frontend-config.yml"
readonly default_tauth_script_url="https://cdn.jsdelivr.net/gh/tyemirov/TAuth@v1.0.1/web/tauth.js"
readonly default_hosted_api_base_url="https://llm-crossword-api.mprlab.com"
readonly default_hosted_auth_base_url="https://tauth-api.mprlab.com"

read_env_file_value() {
  local env_file_path="$1"
  local variable_name="$2"

  if [ ! -f "$env_file_path" ]; then
    return 0
  fi

  sed -n "s/^${variable_name}=//p" "$env_file_path" | head -n 1 | tr -d '\r'
}

resolve_local_hecateapi_env_file() {
  printf '%s' "${LOCAL_HECATEAPI_ENV_FILE:-$default_local_hecateapi_env_file}"
}

resolve_hosted_hecateapi_env_file() {
  if [ -n "${HOSTED_HECATEAPI_ENV_FILE:-}" ]; then
    printf '%s' "$HOSTED_HECATEAPI_ENV_FILE"
    return 0
  fi

  if [ -n "${HECATEAPI_ENV_FILE:-}" ]; then
    printf '%s' "$HECATEAPI_ENV_FILE"
    return 0
  fi

  printf '%s' "$default_hosted_hecateapi_env_file"
}

resolve_profile_env_value() {
  local env_file_path="$1"
  local variable_name="$2"
  local fallback_value="${3:-}"
  local resolved_value

  resolved_value="$(read_env_file_value "$env_file_path" "$variable_name")"
  if [ -n "$resolved_value" ]; then
    printf '%s' "$resolved_value"
    return 0
  fi

  printf '%s' "$fallback_value"
}

resolve_profile_runtime_value() {
  local fallback_value="$1"
  shift

  local variable_name
  local resolved_value

  for variable_name in "$@"; do
    resolved_value="${!variable_name:-}"
    if [ -n "$resolved_value" ]; then
      printf '%s' "$resolved_value"
      return 0
    fi
  done

  printf '%s' "$fallback_value"
}

escape_js_string() {
  printf '%s' "$1" | sed \
    -e 's/\\/\\\\/g' \
    -e 's/"/\\"/g'
}

render_runtime_auth_config() {
  local local_billing_provider="$1"
  local local_paddle_environment="$2"
  local local_paddle_client_token="$3"
  local local_api_base_url="$4"
  local local_auth_base_url="$5"
  local local_config_url="$6"
  local local_tauth_script_url="$7"
  local hosted_billing_provider="$8"
  local hosted_paddle_environment="$9"
  local hosted_paddle_client_token="${10}"
  local hosted_api_base_url="${11}"
  local hosted_auth_base_url="${12}"
  local hosted_config_url="${13}"
  local hosted_tauth_script_url="${14}"

  mkdir -p "$(dirname "$runtime_config_path")"

  cat > "$runtime_config_path" <<EOF
// Generated by scripts/render-runtime-auth-config.sh.
// The browser selects the matching browser-safe runtime profile from the current host.
(function initRuntimeAuthConfig(globalScope) {
  "use strict";

  function freezeRuntimeConfig(config) {
    return Object.freeze({
      billing: Object.freeze({
        clientToken: config.billing.clientToken,
        environment: config.billing.environment,
        providerCode: config.billing.providerCode,
      }),
      services: Object.freeze({
        apiBaseUrl: config.services.apiBaseUrl,
        authBaseUrl: config.services.authBaseUrl,
        configUrl: config.services.configUrl,
        tauthScriptUrl: config.services.tauthScriptUrl,
      }),
    });
  }

  function isLoopbackHostname(hostname) {
    return hostname === "localhost" ||
      hostname === "127.0.0.1" ||
      hostname === "::1" ||
      hostname === "[::1]" ||
      hostname.slice(-10) === ".localhost";
  }

  var localhostConfig = freezeRuntimeConfig({
    billing: {
      clientToken: "${local_paddle_client_token}",
      environment: "${local_paddle_environment}",
      providerCode: "${local_billing_provider}",
    },
    services: {
      apiBaseUrl: "${local_api_base_url}",
      authBaseUrl: "${local_auth_base_url}",
      configUrl: "${local_config_url}",
      tauthScriptUrl: "${local_tauth_script_url}",
    },
  });
  var hostedConfig = freezeRuntimeConfig({
    billing: {
      clientToken: "${hosted_paddle_client_token}",
      environment: "${hosted_paddle_environment}",
      providerCode: "${hosted_billing_provider}",
    },
    services: {
      apiBaseUrl: "${hosted_api_base_url}",
      authBaseUrl: "${hosted_auth_base_url}",
      configUrl: "${hosted_config_url}",
      tauthScriptUrl: "${hosted_tauth_script_url}",
    },
  });

  globalScope.HecateRuntimeConfig = isLoopbackHostname(globalScope.location.hostname.toLowerCase())
    ? localhostConfig
    : hostedConfig;
})(window);
EOF
}

main() {
  local local_hecateapi_env_file
  local hosted_hecateapi_env_file
  local local_billing_provider
  local local_paddle_environment
  local local_paddle_client_token
  local local_api_base_url
  local local_auth_base_url
  local local_config_url
  local local_tauth_script_url
  local hosted_billing_provider
  local hosted_paddle_environment
  local hosted_paddle_client_token
  local hosted_api_base_url
  local hosted_auth_base_url
  local hosted_config_url
  local hosted_tauth_script_url

  local_hecateapi_env_file="$(resolve_local_hecateapi_env_file)"
  hosted_hecateapi_env_file="$(resolve_hosted_hecateapi_env_file)"

  local_billing_provider="$(resolve_profile_env_value "$local_hecateapi_env_file" "HECATEAPI_BILLING_PROVIDER")"
  local_paddle_environment="$(resolve_profile_env_value "$local_hecateapi_env_file" "HECATEAPI_PADDLE_ENVIRONMENT")"
  local_paddle_client_token="$(resolve_profile_env_value "$local_hecateapi_env_file" "HECATEAPI_PADDLE_CLIENT_TOKEN")"
  local_api_base_url="$(resolve_profile_runtime_value "" "LOCAL_HECATE_API_BASE_URL")"
  local_auth_base_url="$(resolve_profile_runtime_value "" "LOCAL_HECATE_AUTH_BASE_URL")"
  local_config_url="$(resolve_profile_runtime_value "$default_frontend_config_url" "LOCAL_HECATE_CONFIG_URL")"
  local_tauth_script_url="$(resolve_profile_runtime_value "$default_tauth_script_url" "LOCAL_HECATE_TAUTH_SCRIPT_URL")"

  hosted_billing_provider="$(resolve_profile_env_value "$hosted_hecateapi_env_file" "HECATEAPI_BILLING_PROVIDER")"
  hosted_paddle_environment="$(resolve_profile_env_value "$hosted_hecateapi_env_file" "HECATEAPI_PADDLE_ENVIRONMENT")"
  hosted_paddle_client_token="$(resolve_profile_env_value "$hosted_hecateapi_env_file" "HECATEAPI_PADDLE_CLIENT_TOKEN")"
  hosted_api_base_url="$(resolve_profile_runtime_value "$default_hosted_api_base_url" "HOSTED_HECATE_API_BASE_URL" "HECATE_API_BASE_URL")"
  hosted_auth_base_url="$(resolve_profile_runtime_value "$default_hosted_auth_base_url" "HOSTED_HECATE_AUTH_BASE_URL" "HECATE_AUTH_BASE_URL")"
  hosted_config_url="$(resolve_profile_runtime_value "$default_frontend_config_url" "HOSTED_HECATE_CONFIG_URL" "HECATE_CONFIG_URL")"
  hosted_tauth_script_url="$(resolve_profile_runtime_value "$default_tauth_script_url" "HOSTED_HECATE_TAUTH_SCRIPT_URL" "HECATE_TAUTH_SCRIPT_URL")"

  render_runtime_auth_config \
    "$(escape_js_string "$local_billing_provider")" \
    "$(escape_js_string "$local_paddle_environment")" \
    "$(escape_js_string "$local_paddle_client_token")" \
    "$(escape_js_string "$local_api_base_url")" \
    "$(escape_js_string "$local_auth_base_url")" \
    "$(escape_js_string "$local_config_url")" \
    "$(escape_js_string "$local_tauth_script_url")" \
    "$(escape_js_string "$hosted_billing_provider")" \
    "$(escape_js_string "$hosted_paddle_environment")" \
    "$(escape_js_string "$hosted_paddle_client_token")" \
    "$(escape_js_string "$hosted_api_base_url")" \
    "$(escape_js_string "$hosted_auth_base_url")" \
    "$(escape_js_string "$hosted_config_url")" \
    "$(escape_js_string "$hosted_tauth_script_url")"
}

main "$@"
