#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

readonly runtime_config_path="${RUNTIME_AUTH_CONFIG_PATH:-js/runtime-auth-config.js}"
readonly default_local_crosswordapi_env_file="configs/.env.crosswordapi.local"
readonly default_production_crosswordapi_env_file="configs/.env.crosswordapi.production"
readonly default_tauth_script_url="https://cdn.jsdelivr.net/gh/tyemirov/TAuth@v1.0.1/web/tauth.js"
readonly default_production_api_base_url="https://llm-crossword-api.mprlab.com"
readonly default_production_auth_base_url="https://tauth-api.mprlab.com"

read_env_file_value() {
  local env_file_path="$1"
  local variable_name="$2"

  if [ ! -f "$env_file_path" ]; then
    return 0
  fi

  sed -n "s/^${variable_name}=//p" "$env_file_path" | head -n 1 | tr -d '\r'
}

resolve_crosswordapi_value() {
  local variable_name="$1"
  local resolved_value="${!variable_name:-}"
  local env_file_path

  if [ -n "$resolved_value" ]; then
    printf '%s' "$resolved_value"
    return 0
  fi

  env_file_path="$(resolve_crosswordapi_env_file)"
  resolved_value="$(read_env_file_value "$env_file_path" "$variable_name")"
  printf '%s' "$resolved_value"
}

resolve_runtime_value() {
  local variable_name="$1"
  local fallback_value="${2:-}"
  local resolved_value="${!variable_name:-}"

  if [ -n "$resolved_value" ]; then
    printf '%s' "$resolved_value"
    return 0
  fi

  printf '%s' "$fallback_value"
}

uses_committed_runtime_defaults() {
  case "$runtime_config_path" in
    js/runtime-auth-config.js|./js/runtime-auth-config.js|*/js/runtime-auth-config.js)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

resolve_crosswordapi_env_file() {
  if [ -n "${CROSSWORDAPI_ENV_FILE:-}" ]; then
    printf '%s' "$CROSSWORDAPI_ENV_FILE"
    return 0
  fi

  if uses_committed_runtime_defaults; then
    printf '%s' "$default_production_crosswordapi_env_file"
    return 0
  fi

  printf '%s' "$default_local_crosswordapi_env_file"
}

fail() {
  printf '%s\n' "$1" >&2
  exit 1
}

render_runtime_auth_config() {
  local billing_provider="$1"
  local paddle_environment="$2"
  local paddle_client_token="$3"
  local api_base_url="$4"
  local auth_base_url="$5"
  local config_url="$6"
  local tauth_script_url="$7"

  mkdir -p "$(dirname "$runtime_config_path")"

  cat > "$runtime_config_path" <<EOF
// Generated by scripts/render-runtime-auth-config.sh.
// The committed copy provides Pages-safe defaults and local runs may overwrite it.
(function initRuntimeAuthConfig(globalScope) {
  "use strict";

  globalScope.LLMCrosswordRuntimeConfig = Object.freeze({
    billing: Object.freeze({
      clientToken: "${paddle_client_token}",
      environment: "${paddle_environment}",
      providerCode: "${billing_provider}",
    }),
    services: Object.freeze({
      apiBaseUrl: "${api_base_url}",
      authBaseUrl: "${auth_base_url}",
      configUrl: "${config_url}",
      tauthScriptUrl: "${tauth_script_url}",
    }),
  });
})(window);
EOF
}

main() {
  local billing_provider
  local paddle_environment
  local paddle_client_token
  local site_origin
  local default_api_base_url
  local default_auth_base_url
  local api_base_url
  local auth_base_url
  local config_url
  local tauth_script_url

  billing_provider="$(resolve_crosswordapi_value "CROSSWORDAPI_BILLING_PROVIDER")"
  paddle_environment="$(resolve_crosswordapi_value "CROSSWORDAPI_PADDLE_ENVIRONMENT")"
  paddle_client_token="$(resolve_crosswordapi_value "CROSSWORDAPI_PADDLE_CLIENT_TOKEN")"
  site_origin="$(resolve_runtime_value "SITE_ORIGIN" "")"
  default_api_base_url="$site_origin"
  default_auth_base_url="$site_origin"
  if uses_committed_runtime_defaults; then
    default_api_base_url="$default_production_api_base_url"
    default_auth_base_url="$default_production_auth_base_url"
  fi
  api_base_url="$(resolve_runtime_value "LLM_CROSSWORD_API_BASE_URL" "$default_api_base_url")"
  auth_base_url="$(resolve_runtime_value "LLM_CROSSWORD_AUTH_BASE_URL" "$default_auth_base_url")"
  config_url="$(resolve_runtime_value "LLM_CROSSWORD_CONFIG_URL" "${site_origin%/}/configs/frontend-config.yml")"
  tauth_script_url="$(resolve_runtime_value "LLM_CROSSWORD_TAUTH_SCRIPT_URL" "$default_tauth_script_url")"
  render_runtime_auth_config \
    "$billing_provider" \
    "$paddle_environment" \
    "$paddle_client_token" \
    "$api_base_url" \
    "$auth_base_url" \
    "$config_url" \
    "$tauth_script_url"
}

main "$@"
